using System.Collections.ObjectModel;
using System.Threading.Tasks;

namespace MERG_BackEnd
{
    public class StreetList:IList
    {

        public string Address { get; set; }

        public StreetList()
        {
        }
        public StreetList(string street)
        {
            Address = street;
        }

        public ObservableCollection<IList> GetList()
        {
            var streetList = new ObservableCollection<IList>();
            streetList.Add(new StreetList("9-ojo Forto g."));
            streetList.Add(new StreetList("A.  Domaševičiaus g."));
            streetList.Add(new StreetList("A.  Goštauto g."));
            streetList.Add(new StreetList("A.  ir J. Vokietaičių g."));
            streetList.Add(new StreetList("A.  Jakšto g."));
            streetList.Add(new StreetList("A.  Jaroševičiaus g."));
            streetList.Add(new StreetList("A.  Jonyno g."));
            streetList.Add(new StreetList("A.  Juozapavičiaus g."));
            streetList.Add(new StreetList("A.  Juozapavičiaus pr."));
            streetList.Add(new StreetList("A.  Kojelavičiaus g."));
            streetList.Add(new StreetList("A.  Kulviečio g."));
            streetList.Add(new StreetList("A.  Mackevičiaus g."));
            streetList.Add(new StreetList("A.  Mickevičiaus g."));
            streetList.Add(new StreetList("A.  Paškevič-Ciotkos g."));
            streetList.Add(new StreetList("A.  Povyliaus g."));
            streetList.Add(new StreetList("A.  Purėno g."));
            streetList.Add(new StreetList("A.  Rotundo g."));
            streetList.Add(new StreetList("A.  Smetonos al."));
            streetList.Add(new StreetList("A.  Smetonos g."));
            streetList.Add(new StreetList("A.  Strazdelio g."));
            streetList.Add(new StreetList("A.  Strazdo g."));
            streetList.Add(new StreetList("A.  Stulginskio g."));
            streetList.Add(new StreetList("A.  Vienuolio g."));
            streetList.Add(new StreetList("A.  Vivulskio g."));
            streetList.Add(new StreetList("A.  Šapokos g."));
            streetList.Add(new StreetList("Adolfo Šapokos g."));
            streetList.Add(new StreetList("Aerodromo g."));
            streetList.Add(new StreetList("Aerouosto g."));
            streetList.Add(new StreetList("Aguonų g."));
            streetList.Add(new StreetList("Aido g."));
            streetList.Add(new StreetList("Aido tak."));
            streetList.Add(new StreetList("Ajerų g."));
            streetList.Add(new StreetList("Akmenų g."));
            streetList.Add(new StreetList("Aldonos g."));
            streetList.Add(new StreetList("Algimanto Petro Kavoliuko g."));
            streetList.Add(new StreetList("Algirdo g."));
            streetList.Add(new StreetList("Alksnynės g."));
            streetList.Add(new StreetList("Alsėdžių g."));
            streetList.Add(new StreetList("Aludarių g."));
            streetList.Add(new StreetList("Ankštoji g."));
            streetList.Add(new StreetList("Antakalnio g."));
            streetList.Add(new StreetList("Antanavos g."));
            streetList.Add(new StreetList("Antano Tumėno g."));
            streetList.Add(new StreetList("Antrosios Melnragės g."));
            streetList.Add(new StreetList("Anykščių g."));
            streetList.Add(new StreetList("Apkasų g."));
            streetList.Add(new StreetList("Apolinaro Juozo Povilaičio g."));
            streetList.Add(new StreetList("Architektų g."));
            streetList.Add(new StreetList("Arimų g."));
            streetList.Add(new StreetList("Ariogalos g."));
            streetList.Add(new StreetList("Ateities g."));
            streetList.Add(new StreetList("Ateities tak."));
            streetList.Add(new StreetList("Atžalyno g."));
            streetList.Add(new StreetList("Aukštabalio g."));
            streetList.Add(new StreetList("Aukštaičių a."));
            streetList.Add(new StreetList(" Gedimino g."));
            streetList.Add(new StreetList("Aukštaičių g."));
            streetList.Add(new StreetList("Aukštakalnio g."));
            streetList.Add(new StreetList("Aukštoji g."));
            streetList.Add(new StreetList("Aukų g."));
            streetList.Add(new StreetList("Austėjos g."));
            streetList.Add(new StreetList("Aušros al."));
            streetList.Add(new StreetList("Aušros g."));
            streetList.Add(new StreetList("Aušros Vartų g."));
            streetList.Add(new StreetList("Avižų g."));
            streetList.Add(new StreetList("Ašigalio g."));
            streetList.Add(new StreetList("Bajorų kel.Bajorų Sodų 17-oji g."));
            streetList.Add(new StreetList("Balandžių g."));
            streetList.Add(new StreetList("Balstogės g."));
            streetList.Add(new StreetList("Baltasis skg."));
            streetList.Add(new StreetList("Baltijos g."));
            streetList.Add(new StreetList("Baltijos pr."));
            streetList.Add(new StreetList("Baltikalnio g."));
            streetList.Add(new StreetList("Baltupio g."));
            streetList.Add(new StreetList("Baltų pr."));
            streetList.Add(new StreetList("Bandužių g."));
            streetList.Add(new StreetList("Bangų g."));
            streetList.Add(new StreetList("Baravykų g."));
            streetList.Add(new StreetList("Bartų g."));
            streetList.Add(new StreetList("Bažnyčios g."));
            streetList.Add(new StreetList("Bernardinų g."));
            streetList.Add(new StreetList("Beržų g."));
            streetList.Add(new StreetList("Bijūnų g."));
            streetList.Add(new StreetList("Birbynių g."));
            streetList.Add(new StreetList("Birutės al."));
            streetList.Add(new StreetList("Birutės g."));
            streetList.Add(new StreetList("Birželio 23-iosios g."));
            streetList.Add(new StreetList("Bistryčios g."));
            streetList.Add(new StreetList("Bitininkų g."));
            streetList.Add(new StreetList("Bitėnų g."));
            streetList.Add(new StreetList("Bičiulių g."));
            streetList.Add(new StreetList("Blindžių g."));
            streetList.Add(new StreetList("Bokšto g."));
            streetList.Add(new StreetList("Bokštų g."));
            streetList.Add(new StreetList("Brastos g."));
            streetList.Add(new StreetList("Briedžio g."));
            streetList.Add(new StreetList("Brolių g."));
            streetList.Add(new StreetList("Broniaus Kazio Balučio g."));
            streetList.Add(new StreetList("Brožynų g."));
            streetList.Add(new StreetList("Budelkiemio g."));
            streetList.Add(new StreetList("Budiniškių g."));
            streetList.Add(new StreetList("Buivydiškių g."));
            streetList.Add(new StreetList("Burbiškių g."));
            streetList.Add(new StreetList("Butsargių g."));
            streetList.Add(new StreetList("Ceikinių g."));
            streetList.Add(new StreetList("Centrinė g."));
            streetList.Add(new StreetList("Chemijos g."));
            streetList.Add(new StreetList("D. Poškos g."));
            streetList.Add(new StreetList("Dabintos g."));
            streetList.Add(new StreetList("Dailės g."));
            streetList.Add(new StreetList("Dainavos g."));
            streetList.Add(new StreetList("Dainų g."));
            streetList.Add(new StreetList("Danielių g."));
            streetList.Add(new StreetList("Danutės g."));
            streetList.Add(new StreetList("Danės g."));
            streetList.Add(new StreetList("Darbininkų g."));
            streetList.Add(new StreetList("Darbo g."));
            streetList.Add(new StreetList("Darbėnų pl."));
            streetList.Add(new StreetList("Dariaus Gerbutavičiaus g."));
            streetList.Add(new StreetList("Dariaus ir Girėno g."));
            streetList.Add(new StreetList("Darželio g."));
            streetList.Add(new StreetList("Daugėliškio g."));
            streetList.Add(new StreetList("Daugų g."));
            streetList.Add(new StreetList("Debreceno g."));
            streetList.Add(new StreetList("Deltuvos g."));
            streetList.Add(new StreetList("Demokratų g."));
            streetList.Add(new StreetList("Didlaukio g."));
            streetList.Add(new StreetList("Didžioji g."));
            streetList.Add(new StreetList("Didžioji Vandens g."));
            streetList.Add(new StreetList("Dituvos g."));
            streetList.Add(new StreetList("Dobilo 2-oji g."));
            streetList.Add(new StreetList("Dominikonų g."));
            streetList.Add(new StreetList("Dragūnų g."));
            streetList.Add(new StreetList("Draugystės g."));
            streetList.Add(new StreetList("Draugystės pr."));
            streetList.Add(new StreetList("Drebulių g."));
            streetList.Add(new StreetList("Druskininkų g."));
            streetList.Add(new StreetList("Dubijos g."));
            streetList.Add(new StreetList("Duburio g."));
            streetList.Add(new StreetList("Dubysos g."));
            streetList.Add(new StreetList("Durpyno g."));
            streetList.Add(new StreetList("Dvaro g."));
            streetList.Add(new StreetList("Dzūkų g."));
            streetList.Add(new StreetList("Dūkštų g."));
            streetList.Add(new StreetList("Dūmų g."));
            streetList.Add(new StreetList("Džiaugsmo g."));
            streetList.Add(new StreetList("Eitkūnų g."));
            streetList.Add(new StreetList("Eitminų g."));
            streetList.Add(new StreetList("Elbingo g."));
            streetList.Add(new StreetList("Elniakampio g."));
            streetList.Add(new StreetList("Elnių g."));
            streetList.Add(new StreetList("Energetikų g."));
            streetList.Add(new StreetList("Erdvės g."));
            streetList.Add(new StreetList("Erfurto g."));
            streetList.Add(new StreetList("Estų g."));
            streetList.Add(new StreetList("Etmonų g."));
            streetList.Add(new StreetList("Europos pr."));
            streetList.Add(new StreetList("Ežeraičio g."));
            streetList.Add(new StreetList("Ežero g."));
            streetList.Add(new StreetList("Ežerėlių g."));
            streetList.Add(new StreetList("Fabijoniškių g."));
            streetList.Add(new StreetList("Filaretų g."));
            streetList.Add(new StreetList("Fizikų g."));
            streetList.Add(new StreetList("G. D. Kuverto g."));
            streetList.Add(new StreetList("Gabijos g."));
            streetList.Add(new StreetList("Gailašių g."));
            streetList.Add(new StreetList("Galinio Pylimo g."));
            streetList.Add(new StreetList("Galvės g."));
            streetList.Add(new StreetList("Gamyklos g."));
            streetList.Add(new StreetList("Gandrų g."));
            streetList.Add(new StreetList("Ganyklų g."));
            streetList.Add(new StreetList("Gaono g."));
            streetList.Add(new StreetList("Gardino g."));
            streetList.Add(new StreetList("Gargždų g."));
            streetList.Add(new StreetList("Gedimino g."));
            streetList.Add(new StreetList("Gedimino pr."));
            streetList.Add(new StreetList("Gedminų g."));
            streetList.Add(new StreetList("Gedvydžių g."));
            streetList.Add(new StreetList("Gegužių g."));
            streetList.Add(new StreetList("Gegužės 3-osios g."));
            streetList.Add(new StreetList("Geležinio Vilko g."));
            streetList.Add(new StreetList("Geležinkelio g."));
            streetList.Add(new StreetList("Geležinkelio Stoties g."));
            streetList.Add(new StreetList("Gelvonų g."));
            streetList.Add(new StreetList("Geologų g."));
            streetList.Add(new StreetList("Gerosios Vilties g."));
            streetList.Add(new StreetList("Gerovės g."));
            streetList.Add(new StreetList("Giedraičių g."));
            streetList.Add(new StreetList("Gilušio g."));
            streetList.Add(new StreetList("Gineitiškių g."));
            streetList.Add(new StreetList("Gintaro g."));
            streetList.Add(new StreetList("Girios g."));
            streetList.Add(new StreetList("Girulių g."));
            streetList.Add(new StreetList("Gluosnių g."));
            streetList.Add(new StreetList("Grafų Tiškevičių g."));
            streetList.Add(new StreetList("Granito g."));
            streetList.Add(new StreetList("Gražinos g."));
            streetList.Add(new StreetList("Gruzdžių g."));
            streetList.Add(new StreetList("Grįžgatvio g."));
            streetList.Add(new StreetList("Gumbinės g."));
            streetList.Add(new StreetList("Gurių g."));
            streetList.Add(new StreetList("Gvazdikų tak."));
            streetList.Add(new StreetList("Gynėjų g."));
            streetList.Add(new StreetList("Gytarių g."));
            streetList.Add(new StreetList("Gėlių g."));
            streetList.Add(new StreetList("Gūdiškių g."));
            streetList.Add(new StreetList("H. Manto g."));
            streetList.Add(new StreetList("Hermano Zudermano g."));
            streetList.Add(new StreetList("Hipodromo g."));
            streetList.Add(new StreetList("I. Kanto al."));
            streetList.Add(new StreetList("I. Kanto g."));
            streetList.Add(new StreetList("I. Simonaitytės g."));
            streetList.Add(new StreetList("Igno Šimulionio g."));
            streetList.Add(new StreetList("Ilgoji g."));
            streetList.Add(new StreetList("Išganytojo g."));
            streetList.Add(new StreetList("J. Basanavičiaus g."));
            streetList.Add(new StreetList("J. Biliūno g."));
            streetList.Add(new StreetList("J. Franko g."));
            streetList.Add(new StreetList("J. Janonio g."));
            streetList.Add(new StreetList("J. Jasinskio g."));
            streetList.Add(new StreetList("J. Karoso g."));
            streetList.Add(new StreetList("J. Kolaso g."));
            streetList.Add(new StreetList("J. Kubiliaus g."));
            streetList.Add(new StreetList("J. Naujalio g."));
            streetList.Add(new StreetList("J. Piktuižio g."));
            streetList.Add(new StreetList("J. Ralio g."));
            streetList.Add(new StreetList("J. Sondeckio g."));
            streetList.Add(new StreetList("J. Tumo-Vaižganto g."));
            streetList.Add(new StreetList("J. Vienožinskio g."));
            streetList.Add(new StreetList("J. Zauerveino g."));
            streetList.Add(new StreetList("J. Zembrickio g."));
            streetList.Add(new StreetList("Jaunimo g."));
            streetList.Add(new StreetList("Jaunystės g."));
            streetList.Add(new StreetList("Jeronimo Ralio g."));
            streetList.Add(new StreetList("Jeruzalės g."));
            streetList.Add(new StreetList("Jogailos g."));
            streetList.Add(new StreetList("Jonažolių g."));
            streetList.Add(new StreetList("Joniškės g."));
            streetList.Add(new StreetList("Jono Asminavičiaus g."));
            streetList.Add(new StreetList("Jono g."));
            streetList.Add(new StreetList("Jono Pauliaus II g."));
            streetList.Add(new StreetList("Josvainių g."));
            streetList.Add(new StreetList("Jotvingių g."));
            streetList.Add(new StreetList("Julijanavos g."));
            streetList.Add(new StreetList("Juodkrantės g."));
            streetList.Add(new StreetList("Juozo Balčikonio g."));
            streetList.Add(new StreetList("Jurginų g."));
            streetList.Add(new StreetList("Jurgio Baltrušaičio g."));
            streetList.Add(new StreetList("Jurgio Lebedžio g."));
            streetList.Add(new StreetList("Justiniškių g."));
            streetList.Add(new StreetList("Jūratės g."));
            streetList.Add(new StreetList("Jūrininkų pr."));
            streetList.Add(new StreetList("Jūros g."));
            streetList.Add(new StreetList("K. Donelaičio a."));
            streetList.Add(new StreetList(" Kadagių g."));
            streetList.Add(new StreetList("K. Donelaičio g."));
            streetList.Add(new StreetList("K. Kalinausko g."));
            streetList.Add(new StreetList("K. Korsako g."));
            streetList.Add(new StreetList("K. Semenavičiaus g."));
            streetList.Add(new StreetList("K. Čerbulėno g."));
            streetList.Add(new StreetList("Kalniečių g."));
            streetList.Add(new StreetList("Kalniškės g."));
            streetList.Add(new StreetList("Kalno g."));
            streetList.Add(new StreetList("Kalnupės g."));
            streetList.Add(new StreetList("Kalvarijų g."));
            streetList.Add(new StreetList("Kalvos g."));
            streetList.Add(new StreetList("Kanapių g."));
            streetList.Add(new StreetList("Kanklių g."));
            streetList.Add(new StreetList("Kapsų g."));
            streetList.Add(new StreetList("Kapų g."));
            streetList.Add(new StreetList("Karaliaus Mindaugo g."));
            streetList.Add(new StreetList("Karaliaučiaus g."));
            streetList.Add(new StreetList("Karališkas tak."));
            streetList.Add(new StreetList("Kareivinių g."));
            streetList.Add(new StreetList("Kareivių g."));
            streetList.Add(new StreetList("Karių Kapų g."));
            streetList.Add(new StreetList("Karklėnų g."));
            streetList.Add(new StreetList("Karklų g."));
            streetList.Add(new StreetList("Karlskronos a."));
            streetList.Add(new StreetList(" Karlskronos g."));
            streetList.Add(new StreetList("Karmelitų g."));
            streetList.Add(new StreetList("Karmėlavos g."));
            streetList.Add(new StreetList("Kastyčio g."));
            streetList.Add(new StreetList("Katedros g."));
            streetList.Add(new StreetList("Kauno g."));
            streetList.Add(new StreetList("Kazimiero Jelskio g."));
            streetList.Add(new StreetList("Kazimiero Ladygos g."));
            streetList.Add(new StreetList("Kazio Ulvydo g."));
            streetList.Add(new StreetList("Kaziulių g."));
            streetList.Add(new StreetList("Kazliškių g."));
            streetList.Add(new StreetList("Kaštonų g."));
            streetList.Add(new StreetList("Kepėjų g."));
            streetList.Add(new StreetList("Kernavės g."));
            streetList.Add(new StreetList("Kirtavietės g."));
            streetList.Add(new StreetList("Kiškių g."));
            streetList.Add(new StreetList("Klaipėdos g."));
            streetList.Add(new StreetList("Klaipėdos pl."));
            streetList.Add(new StreetList("Klemiškės g."));
            streetList.Add(new StreetList("Klevų al."));
            streetList.Add(new StreetList("Klevų g."));
            streetList.Add(new StreetList("Klojimo g."));
            streetList.Add(new StreetList("Klonio g."));
            streetList.Add(new StreetList("Kniaudiškių g."));
            streetList.Add(new StreetList("Konstitucijos pr."));
            streetList.Add(new StreetList("Kontininkų g."));
            streetList.Add(new StreetList("Kooperacijos g."));
            streetList.Add(new StreetList("Kopų g."));
            streetList.Add(new StreetList("Kosmonautų g."));
            streetList.Add(new StreetList("Kovo 11-osios g."));
            streetList.Add(new StreetList("Kranto al."));
            streetList.Add(new StreetList("Kranto g."));
            streetList.Add(new StreetList("Kreivasis skg."));
            streetList.Add(new StreetList("Kretingos g."));
            streetList.Add(new StreetList("Krivių g."));
            streetList.Add(new StreetList("Kroatų g."));
            streetList.Add(new StreetList("Krokuvos g."));
            streetList.Add(new StreetList("Krymo g."));
            streetList.Add(new StreetList("Kukaveičio g."));
            streetList.Add(new StreetList("Kuncų g."));
            streetList.Add(new StreetList("Kunigiškių g."));
            streetList.Add(new StreetList("Kuosų g."));
            streetList.Add(new StreetList("Kurpių g."));
            streetList.Add(new StreetList("Kurėnų g."));
            streetList.Add(new StreetList("Kuršių g."));
            streetList.Add(new StreetList("Kviečių g."));
            streetList.Add(new StreetList("Kėdainių g."));
            streetList.Add(new StreetList("Kęstučio g."));
            streetList.Add(new StreetList("L. Giros g."));
            streetList.Add(new StreetList("L. Rėzos g."));
            streetList.Add(new StreetList("L. Vaineikio g."));
            streetList.Add(new StreetList("Labdarių g."));
            streetList.Add(new StreetList("Laisvės a."));
            streetList.Add(new StreetList(" Liepų al."));
            streetList.Add(new StreetList("Laisvės al."));
            streetList.Add(new StreetList("Laisvės g."));
            streetList.Add(new StreetList("Laisvės pr."));
            streetList.Add(new StreetList("Laivų skg."));
            streetList.Add(new StreetList("Lankiškės g."));
            streetList.Add(new StreetList("Lantainių g."));
            streetList.Add(new StreetList("Lapių g."));
            streetList.Add(new StreetList("Latako g."));
            streetList.Add(new StreetList("Latvių g."));
            streetList.Add(new StreetList("Laukininkų g."));
            streetList.Add(new StreetList("Lauko g."));
            streetList.Add(new StreetList("Laukų g."));
            streetList.Add(new StreetList("Lazdynėlių g."));
            streetList.Add(new StreetList("Lazdynų g."));
            streetList.Add(new StreetList("Lašupio g."));
            streetList.Add(new StreetList("Leičių g."));
            streetList.Add(new StreetList("Lelijų g."));
            streetList.Add(new StreetList("Lenkų g."));
            streetList.Add(new StreetList("Lentvario g."));
            streetList.Add(new StreetList("Liejyklos g."));
            streetList.Add(new StreetList("Lieknų g."));
            streetList.Add(new StreetList("Liepkalnio g."));
            streetList.Add(new StreetList("Liepojos g."));
            streetList.Add(new StreetList("Lieporių g."));
            streetList.Add(new StreetList("Liepyno g."));
            streetList.Add(new StreetList("Liepų g."));
            streetList.Add(new StreetList("Liepų tak."));
            streetList.Add(new StreetList("Lietuvininkų a."));
            streetList.Add(new StreetList(" Ligoninės g."));
            streetList.Add(new StreetList("Lietuvininkų g."));
            streetList.Add(new StreetList("Linkmenų g."));
            streetList.Add(new StreetList("Linksmoji g."));
            streetList.Add(new StreetList("Linkuvos g."));
            streetList.Add(new StreetList("Lipšio g."));
            streetList.Add(new StreetList("Liubeko g."));
            streetList.Add(new StreetList("Liškiavos g."));
            streetList.Add(new StreetList("Lvovo g."));
            streetList.Add(new StreetList("Lyros g."));
            streetList.Add(new StreetList("Lūšių g."));
            streetList.Add(new StreetList("Lūžų g."));
            streetList.Add(new StreetList("M. Antokolskio g."));
            streetList.Add(new StreetList("M. Daujoto g."));
            streetList.Add(new StreetList("M. Daukšos g."));
            streetList.Add(new StreetList("M. Jankaus g."));
            streetList.Add(new StreetList("M. K. Čiurlionio g."));
            streetList.Add(new StreetList("M. Katkaus g."));
            streetList.Add(new StreetList("M. Mažvydo al."));
            streetList.Add(new StreetList("M. Mažvydo g."));
            streetList.Add(new StreetList("M. Valančiaus g."));
            streetList.Add(new StreetList("Maironio g."));
            streetList.Add(new StreetList("Maironiškių g."));
            streetList.Add(new StreetList("Malonioji g."));
            streetList.Add(new StreetList("Malūnininkų g."));
            streetList.Add(new StreetList("Malūno g."));
            streetList.Add(new StreetList("Malūnų g."));
            streetList.Add(new StreetList("Manufaktūrų g."));
            streetList.Add(new StreetList("Margirio g."));
            streetList.Add(new StreetList("Margių g."));
            streetList.Add(new StreetList("Marijonų g."));
            streetList.Add(new StreetList("Markučių g."));
            streetList.Add(new StreetList("Maumedžių g."));
            streetList.Add(new StreetList("Mažojo Kaimelio g."));
            streetList.Add(new StreetList("Mažojo Londono g."));
            streetList.Add(new StreetList("Mažosios Lietuvos g."));
            streetList.Add(new StreetList("Mechanizatorių g."));
            streetList.Add(new StreetList("Medeinos g."));
            streetList.Add(new StreetList("Medelyno g."));
            streetList.Add(new StreetList("Medvalakio g."));
            streetList.Add(new StreetList("Medžiotojų g."));
            streetList.Add(new StreetList("Meldų g."));
            streetList.Add(new StreetList("Melioratorių a."));
            streetList.Add(new StreetList(" Miesto a."));
            streetList.Add(new StreetList(" Rygos g."));
            streetList.Add(new StreetList("Melioratorių al."));
            streetList.Add(new StreetList("Melioratorių g."));
            streetList.Add(new StreetList("Merkinės g."));
            streetList.Add(new StreetList("Merkio g."));
            streetList.Add(new StreetList("Miglos g."));
            streetList.Add(new StreetList("Mindaugo g."));
            streetList.Add(new StreetList("Minijos g."));
            streetList.Add(new StreetList("Minties g."));
            streetList.Add(new StreetList("Mirnabalio g."));
            streetList.Add(new StreetList("Mituvos g."));
            streetList.Add(new StreetList("Mizarų g."));
            streetList.Add(new StreetList("Miškininkų g."));
            streetList.Add(new StreetList("Miško g."));
            streetList.Add(new StreetList("Miškų g."));
            streetList.Add(new StreetList("Mockaičių g."));
            streetList.Add(new StreetList("Mogiliovo g."));
            streetList.Add(new StreetList("Mokyklos g."));
            streetList.Add(new StreetList("Mokytojų g."));
            streetList.Add(new StreetList("Molainių g."));
            streetList.Add(new StreetList("Molo g."));
            streetList.Add(new StreetList("Molėtų g."));
            streetList.Add(new StreetList("Molėtų pl."));
            streetList.Add(new StreetList("Mosėdžio g."));
            streetList.Add(new StreetList("Motiejiškių g."));
            streetList.Add(new StreetList("Musninkų g."));
            streetList.Add(new StreetList("Muziejaus g."));
            streetList.Add(new StreetList("Mykolo Marcinkevičiaus g."));
            streetList.Add(new StreetList("Mykolo Sleževičiaus g."));
            streetList.Add(new StreetList("Mėguvos g."));
            streetList.Add(new StreetList("Mėsinių g."));
            streetList.Add(new StreetList("Naglio g."));
            streetList.Add(new StreetList("Naikupės g."));
            streetList.Add(new StreetList("Naručio g."));
            streetList.Add(new StreetList("Naugarduko g."));
            streetList.Add(new StreetList("Naujakiemio g."));
            streetList.Add(new StreetList("Naujakurių g."));
            streetList.Add(new StreetList("Naujamiesčio g."));
            streetList.Add(new StreetList("Naujoji g."));
            streetList.Add(new StreetList("Naujoji Uosto g."));
            streetList.Add(new StreetList("Naujojo Sodo g."));
            streetList.Add(new StreetList("Nelindos g."));
            streetList.Add(new StreetList("Nemenčinės pl."));
            streetList.Add(new StreetList("Nemuno g."));
            streetList.Add(new StreetList("Nendrės g."));
            streetList.Add(new StreetList("Neravų g."));
            streetList.Add(new StreetList("Neries g."));
            streetList.Add(new StreetList("Neries krant.P. Plechavičiaus g."));
            streetList.Add(new StreetList("Neringos g."));
            streetList.Add(new StreetList("Neužmirštuolių g."));
            streetList.Add(new StreetList("Nevėžio g."));
            streetList.Add(new StreetList("Nidos g."));
            streetList.Add(new StreetList("Noragiškių g."));
            streetList.Add(new StreetList("Norvegų g."));
            streetList.Add(new StreetList("O. Milašiaus g."));
            streetList.Add(new StreetList("Odminių g."));
            streetList.Add(new StreetList("Olimpiečių g."));
            streetList.Add(new StreetList("Oreivių g."));
            streetList.Add(new StreetList("Otų g."));
            streetList.Add(new StreetList("Ozo g."));
            streetList.Add(new StreetList("P. Cvirkos g."));
            streetList.Add(new StreetList("P. Jakšto g."));
            streetList.Add(new StreetList("P. Lukšio g."));
            streetList.Add(new StreetList("P. Vaičiūno g."));
            streetList.Add(new StreetList("P. Vileišio g."));
            streetList.Add(new StreetList("P. Višinskio g."));
            streetList.Add(new StreetList("P. Širvio g."));
            streetList.Add(new StreetList("P. Žadeikos g."));
            streetList.Add(new StreetList("Pajūrio g."));
            streetList.Add(new StreetList("Pakalnės g."));
            streetList.Add(new StreetList("Palangos g."));
            streetList.Add(new StreetList("Pamario g."));
            streetList.Add(new StreetList("Pamarių g."));
            streetList.Add(new StreetList("Pamėnkalnio g."));
            streetList.Add(new StreetList("Panerių g."));
            streetList.Add(new StreetList("Panevėžio g."));
            streetList.Add(new StreetList("Papilėnų g."));
            streetList.Add(new StreetList("Paplaujos g."));
            streetList.Add(new StreetList("Paribio g."));
            streetList.Add(new StreetList("Parko g."));
            streetList.Add(new StreetList("Partizanų g."));
            streetList.Add(new StreetList("Paryžiaus Komunos g."));
            streetList.Add(new StreetList("Pasieniečių g."));
            streetList.Add(new StreetList("Paukščių tak."));
            streetList.Add(new StreetList("Paupio g."));
            streetList.Add(new StreetList("Pavasario g."));
            streetList.Add(new StreetList("Pavilnionių g."));
            streetList.Add(new StreetList("Pašilaičių g."));
            streetList.Add(new StreetList("Pelesos g."));
            streetList.Add(new StreetList("Pergalės g."));
            streetList.Add(new StreetList("Perkūnkiemio g."));
            streetList.Add(new StreetList("Perlojos g."));
            streetList.Add(new StreetList("Peteliškių g."));
            streetList.Add(new StreetList("Pieninės g."));
            streetList.Add(new StreetList("Pienių g."));
            streetList.Add(new StreetList("Pietinė g."));
            streetList.Add(new StreetList("Pietų g."));
            streetList.Add(new StreetList("Pievų g."));
            streetList.Add(new StreetList("Pievų Tako g."));
            streetList.Add(new StreetList("Pilaitės pr."));
            streetList.Add(new StreetList("Piliakalnio g."));
            streetList.Add(new StreetList("Pilies g."));
            streetList.Add(new StreetList("Pilkalnio g."));
            streetList.Add(new StreetList("Pilėnų g."));
            streetList.Add(new StreetList("Piromonto g."));
            streetList.Add(new StreetList("Pirties g."));
            streetList.Add(new StreetList("Plačioji g."));
            streetList.Add(new StreetList("Plento g."));
            streetList.Add(new StreetList("Plieno g."));
            streetList.Add(new StreetList("Plukių g."));
            streetList.Add(new StreetList("Plytinės g."));
            streetList.Add(new StreetList("Plytų g."));
            streetList.Add(new StreetList("Poilsio g."));
            streetList.Add(new StreetList("Polocko g."));
            streetList.Add(new StreetList("Pramonės g."));
            streetList.Add(new StreetList("Pramonės pr."));
            streetList.Add(new StreetList("Pranciškonų g."));
            streetList.Add(new StreetList("Prancūzų g."));
            streetList.Add(new StreetList("Prezidento g."));
            streetList.Add(new StreetList("Priegliaus g."));
            streetList.Add(new StreetList("Priestočio g."));
            streetList.Add(new StreetList("Prūdiškių g."));
            streetList.Add(new StreetList("Prūsų g."));
            streetList.Add(new StreetList("Puodžių g."));
            streetList.Add(new StreetList("Pupinės g."));
            streetList.Add(new StreetList("Purvynės g."));
            streetList.Add(new StreetList("Putinų g."));
            streetList.Add(new StreetList("Pušyno g."));
            streetList.Add(new StreetList("Pušyno skg."));
            streetList.Add(new StreetList("Pušų g."));
            streetList.Add(new StreetList("Pylimo g."));
            streetList.Add(new StreetList("Pylimėlių g."));
            streetList.Add(new StreetList("R. Kalantos g."));
            streetList.Add(new StreetList("R. Žebenkos g."));
            streetList.Add(new StreetList("Radviliškio g."));
            streetList.Add(new StreetList("Radvilų g."));
            streetList.Add(new StreetList("Ragainės g."));
            streetList.Add(new StreetList("Raguvos tak."));
            streetList.Add(new StreetList("Rambyno g."));
            streetList.Add(new StreetList("Ramioji g."));
            streetList.Add(new StreetList("Ramučių g."));
            streetList.Add(new StreetList("Ramygalos g."));
            streetList.Add(new StreetList("Raseinių g."));
            streetList.Add(new StreetList("Rasos g."));
            streetList.Add(new StreetList("Rasų g."));
            streetList.Add(new StreetList("Rato g."));
            streetList.Add(new StreetList("Raudondvario pl."));
            streetList.Add(new StreetList("Raudonės g."));
            streetList.Add(new StreetList("Raugyklos g."));
            streetList.Add(new StreetList("Reikjaviko g."));
            streetList.Add(new StreetList("Respublikos g."));
            streetList.Add(new StreetList("Rimkų g."));
            streetList.Add(new StreetList("Rinktinės g."));
            streetList.Add(new StreetList("Rolando Jankausko g."));
            streetList.Add(new StreetList("Rugių g."));
            streetList.Add(new StreetList("Ruklio g."));
            streetList.Add(new StreetList("Rumpiškės g."));
            streetList.Add(new StreetList("Ruonių g."));
            streetList.Add(new StreetList("Rygos g."));
            streetList.Add(new StreetList("Ryto g."));
            streetList.Add(new StreetList("Ryšininkų g."));
            streetList.Add(new StreetList("Rūdninkų g."));
            streetList.Add(new StreetList("Rūdės g."));
            streetList.Add(new StreetList("Rūko g."));
            streetList.Add(new StreetList("Rūtų g."));
            streetList.Add(new StreetList("S. Dariaus ir S. Girėno g."));
            streetList.Add(new StreetList("S. Daukanto g."));
            streetList.Add(new StreetList("S. Konarskio g."));
            streetList.Add(new StreetList("S. Moniuškos g."));
            streetList.Add(new StreetList("S. Nėries g."));
            streetList.Add(new StreetList("S. Skapo g."));
            streetList.Add(new StreetList("S. Stanevičiaus g."));
            streetList.Add(new StreetList("S. Šalkauskio g."));
            streetList.Add(new StreetList("S. Šimkaus g."));
            streetList.Add(new StreetList("S. Žukausko g."));
            streetList.Add(new StreetList("Salaspilio g."));
            streetList.Add(new StreetList("Salduvės g."));
            streetList.Add(new StreetList("Salomėjos Nėries g."));
            streetList.Add(new StreetList("Santariškių g."));
            streetList.Add(new StreetList("Saulėlydžio g."));
            streetList.Add(new StreetList("Saulės g."));
            streetList.Add(new StreetList("Saulės tak."));
            streetList.Add(new StreetList("Saulėtekio al."));
            streetList.Add(new StreetList("Saulėtekio tak."));
            streetList.Add(new StreetList("Sausio 13-osios g."));
            streetList.Add(new StreetList("Sausio 15-osios g."));
            streetList.Add(new StreetList("Sausoji g."));
            streetList.Add(new StreetList("Savanorių g."));
            streetList.Add(new StreetList("Savanorių pr."));
            streetList.Add(new StreetList("Savičiaus g."));
            streetList.Add(new StreetList("Sedos g."));
            streetList.Add(new StreetList("Seinų g."));
            streetList.Add(new StreetList("Senasis Ukmergės kel."));
            streetList.Add(new StreetList("Senoji g."));
            streetList.Add(new StreetList("Senoji Smiltelės g."));
            streetList.Add(new StreetList("Senvagės g."));
            streetList.Add(new StreetList("Sermiesčio g."));
            streetList.Add(new StreetList("Sevastopolio g."));
            streetList.Add(new StreetList("Siauroji g."));
            streetList.Add(new StreetList("Sibiro g."));
            streetList.Add(new StreetList("Siesikų g."));
            streetList.Add(new StreetList("Sirupio g."));
            streetList.Add(new StreetList("Skardžio g."));
            streetList.Add(new StreetList("Skautų g."));
            streetList.Add(new StreetList("Skinijos g."));
            streetList.Add(new StreetList("Skroblų g."));
            streetList.Add(new StreetList("Skvero g."));
            streetList.Add(new StreetList("Smilgų g."));
            streetList.Add(new StreetList("Smiltelės g."));
            streetList.Add(new StreetList("Smilties Pylimo g."));
            streetList.Add(new StreetList("Smiltynės g."));
            streetList.Add(new StreetList("Smolensko g."));
            streetList.Add(new StreetList("Smėlio g."));
            streetList.Add(new StreetList("Smėlynės g."));
            streetList.Add(new StreetList("Sodų g."));
            streetList.Add(new StreetList("Spaudos g."));
            streetList.Add(new StreetList("Spindulio g."));
            streetList.Add(new StreetList("Sportininkų g."));
            streetList.Add(new StreetList("Sporto g."));
            streetList.Add(new StreetList("Stalupėnų g."));
            streetList.Add(new StreetList("Staniūnų g."));
            streetList.Add(new StreetList("Statybininkų g."));
            streetList.Add(new StreetList("Statybininkų pr."));
            streetList.Add(new StreetList("Stiklių g."));
            streetList.Add(new StreetList("Stiklo g."));
            streetList.Add(new StreetList("Stirnų g."));
            streetList.Add(new StreetList("Stoties g."));
            streetList.Add(new StreetList("Strėvos g."));
            streetList.Add(new StreetList("Studentų g."));
            streetList.Add(new StreetList("Subačiaus g."));
            streetList.Add(new StreetList("Sudervės g."));
            streetList.Add(new StreetList("Sulupės g."));
            streetList.Add(new StreetList("Suvalkų g."));
            streetList.Add(new StreetList("Svajonių g."));
            streetList.Add(new StreetList("Svencelės g."));
            streetList.Add(new StreetList("Sėlių g."));
            streetList.Add(new StreetList("T. Kosciuškos g."));
            streetList.Add(new StreetList("T. Vrublevskio g."));
            streetList.Add(new StreetList("T. Ševčenkos g."));
            streetList.Add(new StreetList("Taikos g."));
            streetList.Add(new StreetList("Taikos pr."));
            streetList.Add(new StreetList("Tarandės g."));
            streetList.Add(new StreetList("Tauralaukio g."));
            streetList.Add(new StreetList("Taurijos g."));
            streetList.Add(new StreetList("Tauro g."));
            streetList.Add(new StreetList("Teatro g."));
            streetList.Add(new StreetList("Tekstilininkų g."));
            streetList.Add(new StreetList("Tenorų g."));
            streetList.Add(new StreetList("Tiesioji g."));
            streetList.Add(new StreetList("Tilto g."));
            streetList.Add(new StreetList("Tiltų g."));
            streetList.Add(new StreetList("Tilžės g."));
            streetList.Add(new StreetList("Tolminkiemio g."));
            streetList.Add(new StreetList("Tomo g."));
            streetList.Add(new StreetList("Topolių aklg."));
            streetList.Add(new StreetList("Topolių g."));
            streetList.Add(new StreetList("Totorių g."));
            streetList.Add(new StreetList("Traidenio g."));
            streetList.Add(new StreetList("Trakų g."));
            streetList.Add(new StreetList("Tremtinių g."));
            streetList.Add(new StreetList("Treniotos g."));
            streetList.Add(new StreetList("Trimitų g."));
            streetList.Add(new StreetList("Trinapolio g."));
            streetList.Add(new StreetList("Trumpoji g."));
            streetList.Add(new StreetList("Trumpės g."));
            streetList.Add(new StreetList("Tujų g."));
            streetList.Add(new StreetList("Tulpių g."));
            streetList.Add(new StreetList("Turgaus a."));
            streetList.Add(new StreetList(" Turgaus g."));
            streetList.Add(new StreetList("Turgaus g."));
            streetList.Add(new StreetList("Turistų g."));
            streetList.Add(new StreetList("Turniškių g."));
            streetList.Add(new StreetList("Tuskulėnų g."));
            streetList.Add(new StreetList("Tverečiaus g."));
            streetList.Add(new StreetList("Tvirtovės g."));
            streetList.Add(new StreetList("Tyrulių g."));
            streetList.Add(new StreetList("Tyzenhauzų g."));
            streetList.Add(new StreetList("Ukmergės g."));
            streetList.Add(new StreetList("Ulonų g."));
            streetList.Add(new StreetList("Universiteto g."));
            streetList.Add(new StreetList("Upelio g."));
            streetList.Add(new StreetList("Upytės g."));
            streetList.Add(new StreetList("Utenos g."));
            streetList.Add(new StreetList("Užkanavės g."));
            streetList.Add(new StreetList("Užupio g."));
            streetList.Add(new StreetList("V. Dambrausko g."));
            streetList.Add(new StreetList("V. Grinkevičiaus g."));
            streetList.Add(new StreetList("V. Grybo g."));
            streetList.Add(new StreetList("V. Krėvės g."));
            streetList.Add(new StreetList("V. Krėvės pr."));
            streetList.Add(new StreetList("V. Kudirkos g."));
            streetList.Add(new StreetList("V. Landsbergio-Žemkalnio g."));
            streetList.Add(new StreetList("V. Nagevičiaus g."));
            streetList.Add(new StreetList("V. Pietario g."));
            streetList.Add(new StreetList("V. Putvinskio g."));
            streetList.Add(new StreetList("V. Šopeno g."));
            streetList.Add(new StreetList("Vaduvos g."));
            streetList.Add(new StreetList("Vaidaugų g."));
            streetList.Add(new StreetList("Vaivorykštės g."));
            streetList.Add(new StreetList("Vaižganto g."));
            streetList.Add(new StreetList("Valaukio g."));
            streetList.Add(new StreetList("Valonų g."));
            streetList.Add(new StreetList("Valstiečių g."));
            streetList.Add(new StreetList("Vanagupės g."));
            streetList.Add(new StreetList("Vandentiekio g."));
            streetList.Add(new StreetList("Varpo g."));
            streetList.Add(new StreetList("Varpų g."));
            streetList.Add(new StreetList("Varėnos g."));
            streetList.Add(new StreetList("Vasario 16-osios g."));
            streetList.Add(new StreetList("Vasaros g."));
            streetList.Add(new StreetList("Vašingtono a."));
            streetList.Add(new StreetList(" Verkių g."));
            streetList.Add(new StreetList("Vegerių g."));
            streetList.Add(new StreetList("Veisiejų g."));
            streetList.Add(new StreetList("Verkių Riešės g."));
            streetList.Add(new StreetList("Verpėjų g."));
            streetList.Add(new StreetList("Vido Maciulevičiaus g."));
            streetList.Add(new StreetList("Viduklės g."));
            streetList.Add(new StreetList("Vienkiemio g."));
            streetList.Add(new StreetList("Vieversių g."));
            streetList.Add(new StreetList("Vilhelmo Berbomo g."));
            streetList.Add(new StreetList("Vilkpėdės g."));
            streetList.Add(new StreetList("Vilkynės g."));
            streetList.Add(new StreetList("Vilniaus al."));
            streetList.Add(new StreetList("Vilniaus g."));
            streetList.Add(new StreetList("Vilties g."));
            streetList.Add(new StreetList("Vinco Kudirkos g."));
            streetList.Add(new StreetList("Vingio g."));
            streetList.Add(new StreetList("Vingrių g."));
            streetList.Add(new StreetList("Virbalio g."));
            streetList.Add(new StreetList("Virbeliškių g."));
            streetList.Add(new StreetList("Virginijaus Druskio g."));
            streetList.Add(new StreetList("Viršuliškių g."));
            streetList.Add(new StreetList("Viršutinė g."));
            streetList.Add(new StreetList("Visorių g."));
            streetList.Add(new StreetList("Visų Šventųjų g."));
            streetList.Add(new StreetList("Vito Gerulaičio g."));
            streetList.Add(new StreetList("Vokiečių g."));
            streetList.Add(new StreetList("Volungės g."));
            streetList.Add(new StreetList("Vydūno g."));
            streetList.Add(new StreetList("Vykinto g."));
            streetList.Add(new StreetList("Vytauto Didžiojo g."));
            streetList.Add(new StreetList("Vytauto g."));
            streetList.Add(new StreetList("Vytauto pr."));
            streetList.Add(new StreetList("Vytauto Vaitkaus g."));
            streetList.Add(new StreetList("Vytenio g."));
            streetList.Add(new StreetList("Vyturio g."));
            streetList.Add(new StreetList("Vyturių g."));
            streetList.Add(new StreetList("Vytėnų g."));
            streetList.Add(new StreetList("Vėtros g."));
            streetList.Add(new StreetList("Vėtrungės g."));
            streetList.Add(new StreetList("Vėžių g."));
            streetList.Add(new StreetList("Z. Sierakausko g."));
            streetList.Add(new StreetList("Zanavykų g."));
            streetList.Add(new StreetList("Zarasų g."));
            streetList.Add(new StreetList("Ąžuolų g."));
            streetList.Add(new StreetList("Č. Sugiharos g."));
            streetList.Add(new StreetList("Čiobiškio g."));
            streetList.Add(new StreetList("Įgulos g."));
            streetList.Add(new StreetList("Įmonių g."));
            streetList.Add(new StreetList("Įsruties g."));
            streetList.Add(new StreetList("Šaltinio g."));
            streetList.Add(new StreetList("Šaltinių g."));
            streetList.Add(new StreetList("Šaltkalvių g."));
            streetList.Add(new StreetList("Šarkuvos g."));
            streetList.Add(new StreetList("Šarlotės g."));
            streetList.Add(new StreetList("Šaulių g."));
            streetList.Add(new StreetList("Šeduvos g."));
            streetList.Add(new StreetList("Šermukšnių g."));
            streetList.Add(new StreetList("Šeškinės g."));
            streetList.Add(new StreetList("Šeškinės Sodų g."));
            streetList.Add(new StreetList("Šiaulių g."));
            streetList.Add(new StreetList("Šiaulių Senoji g."));
            streetList.Add(new StreetList("Šiaurės pr."));
            streetList.Add(new StreetList("Šienpjovių g."));
            streetList.Add(new StreetList("Šilelių g."));
            streetList.Add(new StreetList("Šilo g."));
            streetList.Add(new StreetList("Šiltnamių g."));
            streetList.Add(new StreetList("Šilupio g."));
            streetList.Add(new StreetList("Šilutės g."));
            streetList.Add(new StreetList("Šilutės pl."));
            streetList.Add(new StreetList("Šilūno g."));
            streetList.Add(new StreetList("Širvintų g."));
            streetList.Add(new StreetList("Šlaito g."));
            streetList.Add(new StreetList("Šturmanų g."));
            streetList.Add(new StreetList("Šv. Dvasios g."));
            streetList.Add(new StreetList("Šv. Ignoto g."));
            streetList.Add(new StreetList("Šv. Jokūbo g."));
            streetList.Add(new StreetList("Šv. Jono g."));
            streetList.Add(new StreetList("Šv. Mikalojaus g."));
            streetList.Add(new StreetList("Šv. Mykolo g."));
            streetList.Add(new StreetList("Šv. Stepono g."));
            streetList.Add(new StreetList("Šventosios g."));
            streetList.Add(new StreetList("Švenčionėlių g."));
            streetList.Add(new StreetList("Šviesos g."));
            streetList.Add(new StreetList("Švitrigailos g."));
            streetList.Add(new StreetList("Švyturio g."));
            streetList.Add(new StreetList("Šėtos g."));
            streetList.Add(new StreetList("Ūmėdžių g."));
            streetList.Add(new StreetList("Ūniškių g."));
            streetList.Add(new StreetList("Žalgirio g."));
            streetList.Add(new StreetList("Žalioji g."));
            streetList.Add(new StreetList("Žaliūkių g."));
            streetList.Add(new StreetList("Žaliųjų Ežerų g."));
            streetList.Add(new StreetList("Žardininkų g."));
            streetList.Add(new StreetList("Žarėnų g."));
            streetList.Add(new StreetList("Žeimių g."));
            streetList.Add(new StreetList("Želmenų g."));
            streetList.Add(new StreetList("Žemaitijos g."));
            streetList.Add(new StreetList("Žemaitės g."));
            streetList.Add(new StreetList("Žemaičių g."));
            streetList.Add(new StreetList("Žemynos g."));
            streetList.Add(new StreetList("Žiburio g."));
            streetList.Add(new StreetList("Žiedų skg."));
            streetList.Add(new StreetList("Žilvino g."));
            streetList.Add(new StreetList("Žilvičių g."));
            streetList.Add(new StreetList("Žiogų g."));
            streetList.Add(new StreetList("Žirgo g."));
            streetList.Add(new StreetList("Žirmūnų g."));
            streetList.Add(new StreetList("Žirnių g."));
            streetList.Add(new StreetList("Žolynų g."));
            streetList.Add(new StreetList("Žvejų g."));
            streetList.Add(new StreetList("Žydų g."));
            streetList.Add(new StreetList("Žygimanto Liauksmino g."));
            streetList.Add(new StreetList("Žygimantų g."));
            streetList.Add(new StreetList("Žygio g."));

            return streetList;
        }
    }
}
